### ISSUE TITLE
Vuejs

### ISSUE THREAD

**Issue by kevinstory** [wooorm/nspell#15] opened 2019-04-14 21:55 UTC
I'm trying to create a vue.js SPA with this module. I can't seem to get it to work and was wondering if you know what I'm doing wrong?

```
[HMR] Waiting for update signal from WDS...
index.js?ef10:15 Uncaught TypeError: read is not a function
    at one (index.js?ef10:15)
    at load (index.js?ef10:11)
    at Function.Vue.use (vue.runtime.esm.js?2b0e:5103)
    at eval (main.js?56d7:9)
    at Module../src/main.js (app.js:2552)
    at __webpack_require__ (app.js:724)
    at fn (app.js:101)
    at Object.1 (app.js:2566)
    at __webpack_require__ (app.js:724)
    at app.js:791
one @ index.js?ef10:15
load @ index.js?ef10:11
Vue.use @ vue.runtime.esm.js?2b0e:5103
(anonymous) @ main.js?56d7:9
./src/main.js @ app.js:2552
__webpack_require__ @ app.js:724
fn @ app.js:101
1 @ app.js:2566
__webpack_require__ @ app.js:724
(anonymous) @ app.js:791
(anonymous) @ app.js:794
```

It seems to be referencing the variable "read" in the following: 

```
function one(name) {
    read(join(__dirname, 'index.' + name), function (err, doc) {
      pos++;
      exception = exception || err;
      result[name] = doc;
      if (pos) {
        callback(exception, exception ? null : result);
        exception = null;
        result = null;
      }
    });
  }
```

**Comment by wooorm** [comment] 2019-04-16 16:45
This is not an error with nspell, so I’ll close this. Nor is it a problem with dictionaries.
The problem is that you need to load the files in the browser, which isn’t supported for dictionaries. I don’t suggest doing spelling in the browser because it puts unnecessary big files into your bundle.
You can do it though, but how you include `index.dic` and `index.aff` in the browser depends on your bundler. If using browserify, something like [brfs](https://github.com/browserify/brfs) works.

**Closed by wooorm** 2019-04-16 16:45 UTC
