### ISSUE TITLE
Swedish dictionary seems to not load correctly

### ISSUE THREAD

**Issue by kelj171998** [wooorm/nspell#21] opened 2020-04-25 21:25 UTC
**Defect title:** 
Swedish dictionary seems to don't detect if word is spellt incorrectly and takes nonsense as correct

**Description:**
When trying to load the Swedish dictionary the spell.correct takes any nonsense input
as correct and returns true. Even a word that is not even in the .DIC or .AFF file.

**Steps-to-reproduce:**
1. npm install dictionary-sv
2. Use this code https://www.npmjs.com/package/nspell#usage
3. Change at the top to require('dictionary-sv')
4. Run using: node filename.js

**Expected behvaiour:**
Nspell should return that nonsense or incorrect spellings as false

**Code for defect:**
```js
var dictionary = require('dictionary-sv')
var nspell = require('nspell')

dictionary(ondictionary)
function ondictionary(err, dict) {
  if (err) {
    throw err
  }
  var spell = nspell(dict);
  let nonsense = 'gegetr13';
  let hej = 'hje';
  let hejda = 'hejdåå';
  console.log('Input: ', nonsense, '\t| Expected: false \t| Actual: ', spell.correct('gegetr13'));
  console.log('Input: ', hej, '\t\t| Expected: false \t| Actual: ', spell.correct(hej));
  console.log('Input: ', hejda, '\t\t| Expected: false \t| Actual: ', spell.correct(hejda));
  console.log('Input: ', hej, '\t\t| Expected: [\'hej\'] \t| Actual: ', spell.suggest(hej));
}
```

**Attachments:**
![swedish_dictionary_not_loading_properly](https://user-images.githubusercontent.com/44838262/80291197-e5726d80-874b-11ea-818b-bcd2750e6afb.JPG)

**Comment by kelj171998** [comment] 2020-04-26 10:41
The Swedish dictionary file is probably what is broken when installing via: 
npm install dictionary-swedish

Otherwise, it worked perfectly when testing with another Swedish dictionary from:
https://github.com/titoBouzout/Dictionaries¨

So you probably just need to update the .DIC and .AFF to a new version.

**Comment by wooorm** [comment] 2020-06-25 12:24
Hi! As you report the problem is `dictionary-swedish`, I’ll close this issue, because no changes in `nspell` need to be made.
Thanks!

**Closed by wooorm** 2020-06-25 12:24 UTC
